version: "3"
services:
  forestswar:
    container_name: forestswar
    image: forestswar
    restart: always
    build: .
    ports:
      - "7500:7500"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'
