version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'

  forestswar:
    container_name: forestswar
    image: forestswar
    restart: on-failure
    build: .
    ports:
      - "7500:7500"
    links:
      - mongo
