version: "3"
services:
  forestswar:
    container_name: forestswar
    image: forestswar
    build: .
    ports:
      - "7500:7500"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'
